---
- name: "Creates backend directory"
  become: true
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  become: true
  copy:
    src: artifact.tar.gz
    dest: "~/backend/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  become: true
  shell: |
    cd ~/backend
    tar -xvf artifact.tar.gz
    ls .
    rm -rf artifact.tar.gz
- name: start app
  become: yes
  shell: |
    cd ~/backend
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: database-1.crxy0cbhkjib.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: mypassword
    TYPEORM_DATABASE: postgres    
- name: "Set pm2 start as service"
  become: yes
  shell: |
    cd ~/backend
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
- name: check pm2 status
  become: yes
  shell: |
    cd ~/backend
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines
#- name: "Install dependencies for project"
#  become: true
#  shell: |
#    cd ~/backend
#    ls .
#    npm install -g npm-install-peers
#    npm i -g pm2   
#- name: "start npm"
#  become: true
#  shell: |
#    cd ~/backend
#    pm2 start npm -- start > /dev/null
#    sleep 30
